#pragma once
//       position
//   x      y          z
    0.0f, -0.5f,     0.0f,  //A 0, alsó csúcs

    //8 szög csúcsai
    0.3f,  0.0f,     0.0f,  //B 1
 0.2121f,  0.0f,  0.2121f,  //C 2
    0.0f,  0.0f,     0.3f,  //D 3
-0.2121f,  0.0f,  0.2121f,  //E 4
   -0.3f,  0.0f,     0.0f,  //F 5
-0.2121f,  0.0f, -0.2121f,  //G 6
    0.0f,  0.0f,    -0.3f,  //H 7
 0.2121f,  0.0f, -0.2121f,  //I 8

    0.0f,  0.5f,     0.0f,  //J 9 felső csúcs